#!/usr/bin/fish

set args_txt (cd impl; and ./register.fish | grep SSR_ARGS ; cd ..)
set args (string split ' ' "$args_txt")
test (count $args) = 4
    or begin
        echo failed to fetch ssr param
        exit 1
    end

set password $args[2]
set obfs_param $args[3]
set protocol_param $args[4]

echo "Got SSR parameter: $password | $obfs_param | $protocol_param"

for fl in templates/*.sh
    set cont (cat $fl)
    set fl result/(basename $fl)
    echo "#!/bin/bash
# AUTO-Generated by recolic xingmeng fucker
password=\"$password\"
obfs_param=\"$obfs_param\"
protocol_param=\"$protocol_param\"

$cont
" > $fl
    echo "Creating $fl ..."
end

    

