#!/usr/bin/fish
# run this script ONLY ONCE A DAY
# Allows 3 device, and 52GB traffic

cd impl ; and ./register.fish 2>&1 | tee account.log ; cd ..
set args_txt (cat account.log | grep SSR_ARGS)
set args (string split ' ' "$args_txt")
test (count $args) = 4
    or begin
        echo failed to fetch ssr param
        exit 1
    end

set password $args[2]
set obfs_param $args[3]
set protocol_param $args[4]

echo "Got SSR parameter: $password | $obfs_param | $protocol_param"

for fl in templates/*.sh
    set cont (cat $fl)
    set fl result/(basename $fl)
    set tm (date --utc)
    echo "Creating $fl ..."

    echo "#!/bin/bash
# AUTO-Generated by recolic xingmeng fucker, at $tm
password=\"$password\"
obfs_param=\"$obfs_param\"
protocol_param=\"$protocol_param\"

$cont
" > $fl
    chmod +x $fl
end

    

